openapi: 3.0.0
info:
  version: 1.0.0
  title: Simple API
  description: A simple API to illustrate OpenAPI concepts
paths:
  /players:
    get:
      description: Returns a list of players
      responses:
        '200':
          description: Successfully returned a list of players
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Player'
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Player'
      responses:
        '200':
          description: Successfully created a new player
        '400':
          description: Failed to create a new player
components:
  schemas:
    Player:
      type: object
      required:
        - playerId
        - firstname
        - secondname
        - age
        - teamId
      properties:
        playerId:
          type: integer
        firstname:
          type: string
        secondname:
          type: string
        age:
          type: integer
        teamId:
          type: integer