openapi: 3.0.0
info:
  version: 1.0.0
  title: Simple API
  description: A simple API to illustrate OpenAPI concepts
paths:
  /players:
    get:
      description: Returns a list of players
      responses:
        '200':
          description: Successfully returned a list of players
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Player'
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Player'
      responses:
        '200':
          description: Successfully created a new player
        '400':
          description: Failed to create a new player
    put:
      description: Returns a list of players
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Player'
      responses:
        '200':
          description: Successfully returned a list of players
  /players/{playerId}:
    delete:
      description: Deletes a player from the list
      parameters:
        - name: playerId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successfully deleted a player
        '400':
          description: Failed to delete a player
  /teams:
    get:
      description: Returns a list of teams
      responses:
        '200':
          description: Successfully returned a list of teams
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Team'
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Team'
      responses:
        '200':
          description: Successfully created a new team
        '400':
          description: Failed to create a new team
    put:
      description: Returns a list of teams
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Team'
      responses:
        '200':
          description: Successfully returned a list of teams
  /teams/{teamId}:
    delete:
      description: Deletes a team from the list
      parameters:
        - name: teamId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successfully deleted a team
        '400':
          description: Failed to delete a team
components:
  schemas:
    Player:
      type: object
      required:
        - playerId
        - firstname
        - secondname
        - age
        - teamId
      properties:
        playerId:
          type: integer
        firstname:
          type: string
        secondname:
          type: string
        age:
          type: integer
        teamId:
          type: integer
    Team:
      type: object
      required:
        - teamId
        - teamName
      properties:
        teamId:
          type: integer
        teamName:
          type: string
